// Generated by gen_msg
// DO NOT EDIT!

package protocol

import (
	"reflect"

	"github.com/fanjq99/fnet"
)

func init() {

	fnet.RegisterMessageMeta(1, "C2S_TestRequest", reflect.TypeOf((*C2S_TestRequest)(nil)).Elem())

	fnet.RegisterMessageMeta(2, "S2C_TestResponse", reflect.TypeOf((*S2C_TestResponse)(nil)).Elem())

}
